version: '3.7'
services:
  terraform:
    command: apply "/instant-jellyfin/.tfplan"
    build:
      context: .
      dockerfile: ./Dockerfile.terraform
    volumes:
      - type: bind
        source: ./
        target: /instant-jellyfin
    tty: true
    stdin_open: true
