version: '3.7'
services:
  terraform:
    command: destroy
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /instant-jellyfin
    tty: true
    stdin_open: true